### ISSUE TITLE
OpenVSX auto publishing

### ISSUE THREAD

**Issue by MeltyObserver** [AvaloniaUI/AvaloniaVSCode#143]
### Is your feature request related to a problem? Please describe.

The current extension version on OpenVSX is way behind the official release on the microsoft marketplace, I also noticed that in https://github.com/AvaloniaUI/AvaloniaVSCode/issues/52 and https://github.com/AvaloniaUI/AvaloniaVSCode/issues/85 you've been manually publishing the extension to OpenVSX

### Describe the solution you'd like

OpenVSX provides a free "Auto Publishing" service that automatically syncs extensions on the microsoft marketplace with it's registry, all you have to do is submit a pr to add the extension to [the list](<https://github.com/open-vsx/publish-extensions/blob/master/extensions.json>)

read more at [openVSX/wiki/Auto-Publishing-Extension](<https://github.com/EclipseFdn/open-vsx.org/wiki/Auto-Publishing-Extensions>)

**Comment by MikeCodesDotNET** [comment]
Whats the benefit of publishing to OpenVSX?

**Comment by MeltyObserver** [comment]
openVSX is just a nice to have option for people who don't want to use the Microsoft service. openVSX is also the default on vscodium and other open source builds of vscode.

**Comment by MikeCodesDotNET** [comment]
Thanks for clarifying. 

Looking at OpenVSX, there is a requirement for being OSS which will change in 2025 as we bring features from Avalonia Accelerate to our IDE tooling. For this reason, it's not worth adding the extension to OpenVSX.

**Comment by Sewer56** [comment]
The actual problem is that according to the VS Code Marketplace [Terms of Use](https://aka.ms/vsmarketplace-ToU), you may only install and use Marketplace Offerings with Visual Studio Products and Services.

In other words, ***forks and non-Microsoft Builds of VSCode are not allowed to use the Marketplace.***

They've been recently hardening their stance on this rule. The (proprietary) C# Dev Kit extension now automatically disables itself if it's not a Microsoft build of Code. And likewise, the ability to download extensions from Marketplace from the browser for manual install was removed. 

The only way to download now is to manually construct links in the form of `https://marketplace.visualstudio.com/_apis/public/gallery/publishers/{publisher}/vsextensions/{packageName}/{version}/vspackage?targetPlatform={os-arch}` , for now....
