### ISSUE TITLE
[VSCode] XAML code completion not working as supposed

### ISSUE THREAD

**Issue by pundang** [AvaloniaUI/AvaloniaVSCode#145]
### Describe the bug

XAML code completion isn't working even after building

![image](https://github.com/user-attachments/assets/883d6892-6cc0-423f-b670-ac4e359ec4a4)

### To Reproduce

1. Create new Avalonia MVVM project
2. Try to use XAML auto completion (without build)
3. Build
4. Try to use XAML auto completion (still not working)

### Avalonia for VS Code

v0.0.31

### Avalonia version

11.2.2

### VS Code version

v1.95.3

### Relevant log output

```shell
2024-11-30 20:10:43.976 [info] [Trace - 8:10:43 PM] Sending notification 'textDocument/didChange'.
2024-11-30 20:10:43.977 [info] [Trace - 8:10:43 PM] Sending request 'textDocument/completion - (20)'.
2024-11-30 20:10:43.984 [info] [Trace - 8:10:43 PM] Received response 'textDocument/completion - (20)' in 7ms.
2024-11-30 20:10:43.990 [info] [Trace - 8:10:43 PM] Sending request 'completionItem/resolve - (21)'.
2024-11-30 20:10:43.997 [info] [Trace - 8:10:43 PM] Received response 'completionItem/resolve - (21)' in 7ms.
```

### Additional context

Im using .NET 9.0 & i have 2 projects in the same solution
![image](https://github.com/user-attachments/assets/6b75c89f-f06f-4953-b949-cb85a88842ae)
![image](https://github.com/user-attachments/assets/9ac3c014-8031-490f-8611-56ca6667e242)

**Comment by pundang** [comment]
When i click the "Build the project" snippet there's new output in the "Avalonia Client" tab

```
2024-11-30 20:29:39.361 [info] [EXT - INFO] Solution data path path: C:\Users\AxelP\AppData\Local\Temp\Wirefetch.sln.json
2024-11-30 20:29:39.408 [info] parser process args: C:\Windows\system32\cmd.exe,/d,/s,/c,"dotnet "c:\Users\AxelP\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.31\solutionParserTool\SolutionParser.dll" "d:\Projects\dotNET\Wirefetch\Wirefetch.sln""
```

**Comment by dabbinavo** [comment]
@pundang, The issue you are experiencing is that the SolutionParser version included with the extension is not wokring with .NET 9 (there is also an existing bug-report for this - https://github.com/prashantvc/SolutionParser/issues/5).

So, in order to correctly address this issue, please change the issue title to include the fact that issue persists in **.NET 9**.

**Workaround**

I was able to fix that in the following way
* Checkout https://github.com/prashantvc/SolutionParser
* Update `TargetFramework` in `./SolutionParser.csproj` to `net9.0`
    _I am unsure if this is really needed_
* Compile with `dotnet publish`
* Make a backup of `%USERPROFILE%/.vscode/extensions/avaloniateam.vscode-avalonia-0.0.31/solutionParserTool`
* Replace all content with the newly compiled output (`./bin/Release/net9.0/publish/`)
* Check if things are working now

**Permanent Fix**

Make avalonia extension working with .NET 9.0

* Update git submodule to ref to the latest SolutionParser HEAD in master
* Ensure that the submodule is build with .net 9
    https://github.com/AvaloniaUI/AvaloniaVSCode/blob/0a873c7f39b48e3809c82174a7b5ab06373fdd82/build.sh#L14
    _Propably also set net9.0 as target framework here_
* Publish new extension

**Comment by dabbinavo** [comment]
> When i click the "Build the project" snippet there's new output in the "Avalonia Client" tab
> 
> ```
> 2024-11-30 20:29:39.361 [info] [EXT - INFO] Solution data path path: C:\Users\AxelP\AppData\Local\Temp\Wirefetch.sln.json
> 2024-11-30 20:29:39.408 [info] parser process args: C:\Windows\system32\cmd.exe,/d,/s,/c,"dotnet "c:\Users\AxelP\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.31\solutionParserTool\SolutionParser.dll" "d:\Projects\dotNET\Wirefetch\Wirefetch.sln""
> ```

@pundang Additional hint. Unfortunately, the vscode extension does not log the output of the process in case of a failure. In order to debug, what is going wrong with the parser unable to finish parsing, you can manually execute the parser process in the integrated vscode terminal. 

In this case:
```sh
dotnet "c:\Users\AxelP\.vscode\extensions\avaloniateam.vscode-avalonia-0.0.31\solutionParserTool\SolutionParser.dll" "d:\Projects\dotNET\Wirefetch\Wirefetch.sln"
```

**Comment by heartacker** [comment]
Can anybody file a release
