### ISSUE TITLE
VS Code marketplace version out of date

### ISSUE THREAD

**Issue by Consumedgrub2** [AvaloniaUI/AvaloniaVSCode#148]
Is it possible to build from the source of this repository on Windows? I want to do this to avoid #40. Normally, I'd just get the latest version from the marketplace, but that version is on [v0.0.31](https://github.com/AvaloniaUI/AvaloniaVSCode/releases/tag/v0.0.31). There are no instructions on how to build on Windows. (Sorry, I've never built a typescript project before) Is it possible to get an updated build published?

**Comment by MeltyObserver** [comment]
you can try with this https://github.com/AvaloniaUI/AvaloniaVSCode/pull/149 or use a virtual machine, WSL or MSYS2 to run the linux script for packaging.

*it doesn't matter if it's packaged on windows or linux, vscode will read it*

**Comment by auxym** [comment]
I have had success building on windows by following the instructions in https://github.com/AvaloniaUI/AvaloniaVSCode/blob/main/CONTRIBUTING.md

The `build.sh` script runs fine using the bash binary that comes with Git For Windows (it's probably on your path already if you have git installed, try `bash build.sh`, otherwise start up git bash and do `./build.sh`).

You will have to install  node.js /  npm and vsce, it appears to be an undocumented requirement, see #139.

**Comment by MikeCodesDotNET** [comment]
I've just pushed an update to the marketplace.
